const GH='https://api.github.com';
const GQL='https://api.github.com/graphql';
const API_VERSION='2026-03-10';

export const attentionScore=({uniqueViews=0,stars=0,watchers=0,forks=0,uniqueClones=0}={})=>Number(uniqueViews)+Number(stars)*10+Number(watchers)*20+Number(forks)*15+Number(uniqueClones)*3;
export const eligibleRepo=(r)=>!!r&&!r.private&&!r.fork&&!r.archived;
export const shardForCron=(cron)=>String(cron||'').startsWith('15 ')?0:1;

const reply=(body,status=200,headers={})=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}});
const cors=(env,req)=>{const allowed=new URL(env.PORTFOLIO_URL).origin;return req.headers.get('origin')===allowed?{'access-control-allow-origin':allowed,'access-control-allow-headers':'authorization, content-type','access-control-allow-methods':'GET, POST, OPTIONS',vary:'Origin'}:{}};
const ghHeaders=(token,extra={})=>({accept:'application/vnd.github+json','x-github-api-version':API_VERSION,'user-agent':'portfolio-github-analytics',authorization:`Bearer ${token}`,...extra});
async function gh(path,env,options={}){const res=await fetch(path.startsWith('http')?path:`${GH}${path}`,{...options,headers:ghHeaders(env.GITHUB_ANALYTICS_TOKEN,options.headers||{})});if(!res.ok)throw new Error(`GitHub ${res.status} ${path}: ${(await res.text()).slice(0,180)}`);return res.status===204?null:res.json();}
async function soft(path,env,fallback){try{return await gh(path,env)}catch(e){console.warn(String(e));return fallback}}

function authorized(req,env){const value=(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,'');return !!env.DASHBOARD_ACCESS_KEY&&value===env.DASHBOARD_ACCESS_KEY;}

async function repos(env){return (await gh(`/users/${env.GITHUB_OWNER}/repos?type=owner&sort=full_name&per_page=100`,env)).filter(eligibleRepo).sort((a,b)=>a.name.localeCompare(b.name));}
async function graphCounts(list,env){if(!list.length)return{};const fields=list.map((r,i)=>`r${i}:repository(owner:${JSON.stringify(env.GITHUB_OWNER)},name:${JSON.stringify(r.name)}){stargazerCount watchers{totalCount} forkCount issues(states:OPEN){totalCount} pullRequests(states:OPEN){totalCount}}`).join('\n');const res=await fetch(GQL,{method:'POST',headers:ghHeaders(env.GITHUB_ANALYTICS_TOKEN,{'content-type':'application/json'}),body:JSON.stringify({query:`query PortfolioAnalytics{${fields}}`})});if(!res.ok)throw new Error(`GitHub GraphQL ${res.status}`);const p=await res.json();if(p.errors?.length)throw new Error(p.errors[0].message);const out={};list.forEach((r,i)=>{const x=p.data?.[`r${i}`]||{};out[r.name]={stars:x.stargazerCount??r.stargazers_count??0,watchers:x.watchers?.totalCount??0,forks:x.forkCount??r.forks_count??0,issues:x.issues?.totalCount??0,prs:x.pullRequests?.totalCount??0};});return out;}

async function trafficDaily(db,repo,views,clones){const map=new Map();for(const x of views?.views||[]){const day=String(x.timestamp||'').slice(0,10);if(day)map.set(day,{day,views:x.count||0,uv:x.uniques||0,clones:0,uc:0});}for(const x of clones?.clones||[]){const day=String(x.timestamp||'').slice(0,10);if(!day)continue;const row=map.get(day)||{day,views:0,uv:0,clones:0,uc:0};row.clones=x.count||0;row.uc=x.uniques||0;map.set(day,row);}if(map.size)await db.batch([...map.values()].map(x=>db.prepare('INSERT INTO traffic_daily(day,repo,views,unique_views,clones,unique_clones) VALUES(?,?,?,?,?,?) ON CONFLICT(day,repo) DO UPDATE SET views=excluded.views,unique_views=excluded.unique_views,clones=excluded.clones,unique_clones=excluded.unique_clones').bind(x.day,repo,x.views,x.uv,x.clones,x.uc)));}
async function discovery(db,repo,day,refs,paths){const q=[db.prepare('DELETE FROM referrers WHERE captured_on=? AND repo=?').bind(day,repo),db.prepare('DELETE FROM popular_paths WHERE captured_on=? AND repo=?').bind(day,repo)];for(const x of refs||[])q.push(db.prepare('INSERT INTO referrers(captured_on,repo,referrer,count,uniques) VALUES(?,?,?,?,?)').bind(day,repo,x.referrer||'unknown',x.count||0,x.uniques||0));for(const x of paths||[])q.push(db.prepare('INSERT INTO popular_paths(captured_on,repo,path,title,count,uniques) VALUES(?,?,?,?,?,?)').bind(day,repo,x.path||'/',x.title||'',x.count||0,x.uniques||0));await db.batch(q);}
async function actors(db,kind,repo,logins,now){const current=new Set(logins.filter(Boolean));const oldRows=await db.prepare('SELECT login FROM actor_state WHERE kind=? AND repo=?').bind(kind,repo).all();const old=new Set((oldRows.results||[]).map(x=>x.login));const baseline=old.size===0;const q=[];for(const login of current){q.push(db.prepare('INSERT INTO actor_state(kind,repo,login,last_seen_at) VALUES(?,?,?,?) ON CONFLICT(kind,repo,login) DO UPDATE SET last_seen_at=excluded.last_seen_at').bind(kind,repo,login,now));if(!baseline&&!old.has(login))q.push(db.prepare('INSERT INTO events(occurred_at,kind,repo,actor,delta) VALUES(?,?,?,?,1)').bind(now,`${kind}_added`,repo,login));}if(!baseline)for(const login of old)if(!current.has(login)){q.push(db.prepare('DELETE FROM actor_state WHERE kind=? AND repo=? AND login=?').bind(kind,repo,login));q.push(db.prepare('INSERT INTO events(occurred_at,kind,repo,actor,delta) VALUES(?,?,?,?, -1)').bind(now,`${kind}_removed`,repo,login));}if(q.length)await db.batch(q);}

async function collectRepo(repo,count,env,now){const name=repo.name;const [views,clones,refs,paths,stars,watchers]=await Promise.all([soft(`/repos/${env.GITHUB_OWNER}/${name}/traffic/views?per=day`,env,{count:0,uniques:0,views:[]}),soft(`/repos/${env.GITHUB_OWNER}/${name}/traffic/clones?per=day`,env,{count:0,uniques:0,clones:[]}),soft(`/repos/${env.GITHUB_OWNER}/${name}/traffic/popular/referrers`,env,[]),soft(`/repos/${env.GITHUB_OWNER}/${name}/traffic/popular/paths`,env,[]),soft(`/repos/${env.GITHUB_OWNER}/${name}/stargazers?per_page=100`,env,[]),soft(`/repos/${env.GITHUB_OWNER}/${name}/subscribers?per_page=100`,env,[])]);const c=count||{stars:repo.stargazers_count||0,watchers:0,forks:repo.forks_count||0,issues:0,prs:0};const score=attentionScore({uniqueViews:views.uniques||0,stars:c.stars,watchers:c.watchers,forks:c.forks,uniqueClones:clones.uniques||0});await env.ANALYTICS_DB.prepare('INSERT INTO repo_snapshots(captured_at,repo,stars,watchers,forks,open_issues,open_prs,views_14d,unique_views_14d,clones_14d,unique_clones_14d,attention) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').bind(now,name,c.stars,c.watchers,c.forks,c.issues,c.prs,views.count||0,views.uniques||0,clones.count||0,clones.uniques||0,score).run();await trafficDaily(env.ANALYTICS_DB,name,views,clones);await discovery(env.ANALYTICS_DB,name,now.slice(0,10),refs,paths);await actors(env.ANALYTICS_DB,'star',name,stars.map(x=>x.user?.login||x.login),now);await actors(env.ANALYTICS_DB,'watcher',name,watchers.map(x=>x.login),now);}
async function collectFollowers(env,now){const [profile,list]=await Promise.all([soft(`/users/${env.GITHUB_OWNER}`,env,{followers:0}),soft(`/users/${env.GITHUB_OWNER}/followers?per_page=100`,env,[])]);await env.ANALYTICS_DB.prepare('INSERT OR REPLACE INTO account_snapshots(captured_at,followers) VALUES(?,?)').bind(now,profile.followers||list.length||0).run();await actors(env.ANALYTICS_DB,'follower','',list.map(x=>x.login),now);}
async function collect(env,shard){if(!env.GITHUB_ANALYTICS_TOKEN)throw new Error('GITHUB_ANALYTICS_TOKEN is not configured');const all=await repos(env);const counts=await graphCounts(all,env).catch(e=>{console.warn(String(e));return{}});const selected=all.filter((_,i)=>i%2===shard);const now=new Date().toISOString();for(const r of selected){try{await collectRepo(r,counts[r.name],env,now)}catch(e){await env.ANALYTICS_DB.prepare('INSERT INTO events(occurred_at,kind,repo,delta,details) VALUES(?,?,?,0,?)').bind(now,'collection_error',r.name,String(e).slice(0,800)).run();}}if(shard===0)await collectFollowers(env,now);return{discovered:all.length,collected:selected.length,shard};}

async function repoRows(db,days){const cutoff=new Date(Date.now()-days*86400000).toISOString();const latest=await db.prepare('WITH r AS(SELECT *,ROW_NUMBER() OVER(PARTITION BY repo ORDER BY captured_at DESC) rn FROM repo_snapshots) SELECT * FROM r WHERE rn=1 ORDER BY attention DESC,repo').all();const base=await db.prepare('WITH r AS(SELECT *,ROW_NUMBER() OVER(PARTITION BY repo ORDER BY captured_at ASC) rn FROM repo_snapshots WHERE captured_at>=?) SELECT repo,stars,watchers,forks,open_prs FROM r WHERE rn=1').bind(cutoff).all();const m=new Map((base.results||[]).map(x=>[x.repo,x]));return(latest.results||[]).map(x=>{const b=m.get(x.repo)||x;return{...x,stars_delta:x.stars-b.stars,watchers_delta:x.watchers-b.watchers,forks_delta:x.forks-b.forks,open_prs_delta:x.open_prs-b.open_prs};});}
async function overview(env,days){const rr=await repoRows(env.ANALYTICS_DB,days);const day=new Date(Date.now()-(days-1)*86400000).toISOString().slice(0,10);const t=await env.ANALYTICS_DB.prepare('SELECT COALESCE(SUM(views),0) views,COALESCE(SUM(unique_views),0) unique_views,COALESCE(SUM(clones),0) clones,COALESCE(SUM(unique_clones),0) unique_clones FROM traffic_daily WHERE day>=?').bind(day).first();const f=await env.ANALYTICS_DB.prepare('SELECT followers,captured_at FROM account_snapshots ORDER BY captured_at DESC LIMIT 1').first();const fb=await env.ANALYTICS_DB.prepare('SELECT followers FROM account_snapshots WHERE captured_at>=? ORDER BY captured_at LIMIT 1').bind(new Date(Date.now()-days*86400000).toISOString()).first();return{days,repositories:rr.length,stars:rr.reduce((n,x)=>n+x.stars,0),starsDelta:rr.reduce((n,x)=>n+x.stars_delta,0),watchers:rr.reduce((n,x)=>n+x.watchers,0),watchersDelta:rr.reduce((n,x)=>n+x.watchers_delta,0),forks:rr.reduce((n,x)=>n+x.forks,0),views:t?.views||0,uniqueViews:t?.unique_views||0,clones:t?.clones||0,uniqueClones:t?.unique_clones||0,followers:f?.followers||0,followersDelta:(f?.followers||0)-(fb?.followers??f?.followers??0),lastCollectedAt:rr.map(x=>x.captured_at).sort().at(-1)||f?.captured_at||null};}
async function series(env,days){const day=new Date(Date.now()-(days-1)*86400000).toISOString().slice(0,10);const t=await env.ANALYTICS_DB.prepare('SELECT day,SUM(views) views,SUM(clones) clones FROM traffic_daily WHERE day>=? GROUP BY day ORDER BY day').bind(day).all();const s=await env.ANALYTICS_DB.prepare('WITH d AS(SELECT substr(captured_at,1,10) day,repo,stars,ROW_NUMBER() OVER(PARTITION BY substr(captured_at,1,10),repo ORDER BY captured_at DESC) rn FROM repo_snapshots WHERE substr(captured_at,1,10)>=?) SELECT day,SUM(stars) stars FROM d WHERE rn=1 GROUP BY day ORDER BY day').bind(day).all();const f=await env.ANALYTICS_DB.prepare('WITH d AS(SELECT substr(captured_at,1,10) day,followers,ROW_NUMBER() OVER(PARTITION BY substr(captured_at,1,10) ORDER BY captured_at DESC) rn FROM account_snapshots WHERE substr(captured_at,1,10)>=?) SELECT day,followers FROM d WHERE rn=1 ORDER BY day').bind(day).all();const m=new Map();for(const x of t.results||[])m.set(x.day,{day:x.day,...x});for(const x of s.results||[])m.set(x.day,{...(m.get(x.day)||{day:x.day}),...x});for(const x of f.results||[])m.set(x.day,{...(m.get(x.day)||{day:x.day}),...x});return[...m.values()].sort((a,b)=>a.day.localeCompare(b.day));}
async function discover(env){const rd=await env.ANALYTICS_DB.prepare('SELECT MAX(captured_on) day FROM referrers').first();const pd=await env.ANALYTICS_DB.prepare('SELECT MAX(captured_on) day FROM popular_paths').first();const r=rd?.day?await env.ANALYTICS_DB.prepare('SELECT referrer,SUM(count) count,SUM(uniques) uniques FROM referrers WHERE captured_on=? GROUP BY referrer ORDER BY count DESC LIMIT 10').bind(rd.day).all():{results:[]};const p=pd?.day?await env.ANALYTICS_DB.prepare('SELECT repo,path,title,count,uniques FROM popular_paths WHERE captured_on=? ORDER BY count DESC LIMIT 15').bind(pd.day).all():{results:[]};return{referrers:r.results||[],paths:p.results||[],capturedOn:rd?.day||pd?.day||null};}

async function api(req,env,path){const h=cors(env,req);if(!authorized(req,env))return reply({error:'Authentication required'},401,h);const u=new URL(req.url),days=Math.max(7,Math.min(90,Number(u.searchParams.get('days')||14)));if(path==='/api/overview')return reply(await overview(env,days),200,h);if(path==='/api/repos')return reply({days,repos:await repoRows(env.ANALYTICS_DB,days)},200,h);if(path==='/api/timeseries')return reply({days,points:await series(env,days)},200,h);if(path==='/api/events'){const r=await env.ANALYTICS_DB.prepare('SELECT occurred_at,kind,repo,actor,delta,details FROM events ORDER BY id DESC LIMIT 100').all();return reply({events:r.results||[]},200,h);}if(path==='/api/discovery')return reply(await discover(env),200,h);if(path==='/api/collect'&&req.method==='POST'){const shard=Number(u.searchParams.get('shard'))===1?1:0;return reply({ok:true,result:await collect(env,shard)},200,h);}return reply({error:'Not found'},404,h);}

export default{async fetch(req,env){const u=new URL(req.url),h=cors(env,req);if(req.method==='OPTIONS')return new Response(null,{status:204,headers:h});if(u.pathname==='/health')return reply({ok:true,service:'portfolio-github-analytics'},200,h);if(u.pathname.startsWith('/api/'))return api(req,env,u.pathname);return reply({error:'Not found'},404,h);},async scheduled(controller,env,ctx){ctx.waitUntil(collect(env,shardForCron(controller.cron)));}};
